- src: alvistack.kube_ingress_nginx
  version: 5.4.0
- src: nginxinc.nginx
  version: 0.24.0
- src: geerlingguy.redis
  version: 1.7.0
- src: geerlingguy.supervisor
  version: 3.0.0
- src: geerlingguy.nodejs
  version: 6.0.0
