<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="currencies">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="exrate" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="lastUpdate" type="xs:date"/>
                            <xs:element name="currency" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="name" type="currencyNameType"/>
                                        <xs:element name="unit" type="unitType"/>
                                        <xs:element name="currencyCode" type="currencyCodeType"/>
                                        <xs:element name="country" type="countryCodeType"/>
                                        <xs:element name="rate" type="rateType"/>
                                        <xs:element name="change" type="changeType"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="currencyNameType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-zA-Z ]+"/>
            <xs:minLength value="2"/>
            <xs:maxLength value="60"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="unitType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="1000000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="currencyCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="countryCodeType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z]{3}"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="rateType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000000000"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="changeType">
        <xs:restriction base="xs:decimal">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="1000000000"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>