[program:pdp_backend]
command="/root/.nvm/versions/node/v20.12.2/bin/node /var/www/{{ project_name }}/current/dist/main.js"
directory="/var/www/{{ project_name }}/current"
autostart=true
autorestart=true
stderr_logfile=/var/log/pdp_backend.err.log
stdout_logfile=/var/log/pdp_backend.out.log
environment=NODE_ENV="production"
user=root
